name: Publish to pub.dev

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

concurrency:
  group: pub-dev-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish:
    permissions:
      contents: read
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@6afc89df92d6eb3834022f73cd65adc8cdfcb92d # v1
    with:
      environment: pub.dev
